# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Set-Scalar
version:      1.20
version_from: lib/Set/Scalar.pm
installdirs:  site
requires:
    Scalar::Util:                  0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
